name: Build and Package DeployTool

on:
  push:
    branches:
      - main  # Trigger the workflow on pushing to the 'main' branch

jobs:
  build_and_package:
    runs-on: ubuntu-latest  # 可以选择 ubuntu 或 windows，根据你的需求

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # 确保检出所有子模块，如果项目包含子模块

    - name: Set up Docker Build Environment
      uses: addnab/docker-run-action@v3
      with:
        image: docker://your-docker-image  # 使用你构建的 Docker 镜像，替换为你自己的镜像
        options: --rm  # 自动清理容器

    - name: Build project in Docker container
      run: |
        # 使用 Dockerfile 构建镜像
        docker build -t my-qt-app .  # 构建 Docker 镜像，my-qt-app 为镜像名称
        # 运行构建命令
        docker run --rm my-qt-app  # 在容器中运行构建命令，确保容器结束后被移除
