name: Build and Test Qt5 Project

on:
  push:
    branches:
      - main  # 可按需修改触发工作流的分支，比如'master'等

jobs:
  build_and_test:
    runs-on: windows-latest  # 选择 Windows 环境，适配代码中 Windows 相关操作
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt5
      uses: jurplel/install-qt-action@v3  # 使用这个 action 来安装 Qt5，更方便，当然你也可以手动写安装步骤，类似 apt-get 安装在 Linux 下那样（参考之前给的示例中 Linux 安装 Qt5 依赖部分，Windows 可以通过 chocolatey 等方式安装）
      with:
        version: 5.15.2  # 修改为你实际使用的 Qt5 版本号
        modules: [core, gui, widgets]  # 根据你的.pro 文件里引入的模块填写

    - name: Build the project using qmake
      run: |
        qmake your_project_name.pro
        nmake  # 在 Windows 下通常用 nmake 构建，如果你项目里配置了使用其他构建工具（如 mingw32-make 等）则替换这里的版本

    - name: Test the application (if applicable)
      run: |
      .\your_app_name.exe  # 运行生成的可执行文件进行测试，这里假设生成的可执行文件在当前目录下且叫 your_app_name.exe，按你实际生成的文件名和路径调整

    - name: Archive build artifacts (optional)
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/your_app_name.exe  # 直接写成普通字符串形式，这里假设生成的可执行文件就在当前目录下，如果实际在其他目录（比如有个build目录下），则写成相对路径，例如：build/your_app_name.exe
