name: Build and Package DeployTool

on:
  push:
    branches:
      - main  # 可以根据实际情况修改触发工作流的分支，比如'master'等

jobs:
  build_and_package:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # 如果项目包含子模块，添加此参数以确保子模块也被拉取

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'  # 根据实际使用的Qt版本进行修改
        platform: win64
        dir: ${{ github.workspace }}/Qt

    - name: Configure build environment
      shell: powershell
      run: |
        $env:PATH += ";${{ github.workspace }}/Qt/5.15.2/msvc2019_64/bin"  # 根据实际安装的Qt版本和编译器修改路径
        [System.Environment]::SetEnvironmentVariable("PATH", $env:PATH, [System.EnvironmentVariableTarget]::Machine)

    - name: Build the project
      shell: powershell
      run: |
        qmake
        nmake  # 如果项目使用的是 MinGW 编译器，则替换为'mingw32-make'

    - name: Package application with windeployqt
      shell: powershell
      run: |
        windeployqt --dir release --force DeployTool.exe  # 假设可执行文件名为DeployTool.exe，根据实际情况修改文件名
        Compress-Archive -Path release/* -DestinationPath DeployTool.zip  # 将打包后的文件压缩为一个 zip 文件方便分发

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: DeployTool
        path: DeployTool.zip  # 上传刚才压缩好的文件作为构建产物
