name: Build and Package DeployTool

on:
  push:
    branches:
      - main

jobs:
  build_and_package:
    runs-on: ubuntu-latest  # 运行在 Ubuntu 环境中，因为 Docker 是跨平台的，Ubuntu 也支持 Docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker build environment
      run: |
        docker build -t deploytool-build-env .  # 使用当前目录下的 Dockerfile 创建镜像

    - name: Run build inside Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace deploytool-build-env powershell -Command "
          cd /workspace/.github/workflows
          if (Test-Path 'DeployTool.pro') {
            qmake .\DeployTool.pro -o ..\build\Makefile  # 使用 qmake 生成 Makefile
            nmake -C ..\build  # 使用 nmake 进行构建
          } else {
            Write-Host 'DeployTool.pro file not found. Please check the path.'
            exit 1
          }
        "

    - name: Package application with windeployqt
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace deploytool-build-env powershell -Command "
          windeployqt --dir build/release --force build/DeployTool.exe
          Compress-Archive -Path build/release/* -DestinationPath build/DeployTool.zip
        "

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: DeployTool
        path: build/DeployTool.zip
